databases:
  - name: pakistani-tax-advisor-db
    plan: free
    databaseName: pakistani_tax_advisor
    user: db_user

services:
  # Backend API
  - type: web
    name: pakistani-tax-advisor-api
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pakistani-tax-advisor-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000

  # Frontend React App
  - type: web
    name: pakistani-tax-advisor-web
    runtime: static
    plan: free
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: ./Frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://pakistani-tax-advisor-api.onrender.com