// Frontend/scripts/sync-shared.js
//
// Create React App's ModuleScopePlugin forbids importing files outside
// Frontend/src/, so the frontend cannot import the repo-root shared/ modules
// directly. Rather than hand-maintaining a duplicate (which silently drifts —
// see the graphify audit 2026-06-07), this script regenerates the in-src
// mirror from the canonical repo-root shared/ copy.
//
// Runs automatically via the prestart/prebuild/pretest npm hooks. The repo-root
// shared/<file> is the SINGLE SOURCE OF TRUTH; the generated mirror under
// src/shared/ must never be edited by hand.

const fs = require('fs');
const path = require('path');

// Files the frontend consumes from repo-root shared/. Add to this list if the
// frontend ever needs expenseSchema.js or wizardFieldMap.js.
const FILES = ['formFieldVisibility.js'];

const ROOT_SHARED = path.join(__dirname, '..', '..', 'shared');
const SRC_SHARED = path.join(__dirname, '..', 'src', 'shared');

const BANNER =
  '// @generated by Frontend/scripts/sync-shared.js — DO NOT EDIT.\n' +
  '// Canonical source: repo-root shared/%FILE%. Edit that file instead;\n' +
  '// this mirror is regenerated on every prestart/prebuild/pretest.\n\n';

fs.mkdirSync(SRC_SHARED, { recursive: true });

for (const file of FILES) {
  const src = path.join(ROOT_SHARED, file);
  const dest = path.join(SRC_SHARED, file);

  // The Docker frontend build context is ./Frontend only (see
  // docker-compose.prod.yml), so repo-root shared/ is NOT present inside the
  // container. In that case fall back to the committed mirror — it was synced
  // at commit time and COPY'd into the image — instead of failing the build.
  if (!fs.existsSync(src)) {
    if (fs.existsSync(dest)) {
      console.warn(`[sync-shared] canonical source absent (${src}); using committed mirror src/shared/${file}`);
      continue;
    }
    console.error(`[sync-shared] missing BOTH canonical source and mirror for ${file}`);
    process.exit(1);
  }

  const body = fs.readFileSync(src, 'utf8');
  fs.writeFileSync(dest, BANNER.replace('%FILE%', file) + body, 'utf8');
  console.log(`[sync-shared] ${file} -> src/shared/${file}`);
}
