import React from 'react';
import LegalLayout, { H2, P, UL, LI, Callout, CONTACT_EMAIL } from './LegalLayout';

export default function UserAgreement() {
  return (
    <LegalLayout
      title="User Agreement"
      subtitle="Your consent to use MeraTax, and a clear statement of what you and we are each responsible for."
    >
      <Callout>
        This is the agreement you accept before entering the app. It works alongside our Terms &amp; Conditions
        and Privacy Policy and explains, in plain terms, the basis on which you use MeraTax.
      </Callout>

      <H2>1. Your consent</H2>
      <P>
        By accepting this User Agreement and continuing into the app, you confirm that you have read and agree
        to this Agreement, the Terms &amp; Conditions, and the Privacy Policy, and that you consent to MeraTax
        processing your personal and financial information to provide the Service.
      </P>

      <H2>2. MeraTax is a self-service tool</H2>
      <P>
        MeraTax assists you in preparing your own Pakistani income tax return. It is software — not a tax
        agent, accountant, lawyer, or representative. Using MeraTax does not create a professional advisory or
        fiduciary relationship between you and MeraTax.
      </P>

      <H2>3. Your responsibilities</H2>
      <UL>
        <LI>Provide accurate, complete, and truthful information.</LI>
        <LI>Review every calculation and figure before relying on it or filing your return.</LI>
        <LI>Keep your own supporting records and documentation.</LI>
        <LI>Make the final decisions about your return and your filing.</LI>
        <LI>Keep your login credentials confidential and secure.</LI>
      </UL>

      <H2>4. What you acknowledge</H2>
      <UL>
        <LI>Tax calculations are generated by software based on the applicable Finance Act and the information you enter, and may not cover every individual circumstance.</LI>
        <LI>MeraTax is not affiliated with or endorsed by the FBR, and acceptance of a return by the FBR is outside our control.</LI>
        <LI>You are responsible for any tax, penalty, surcharge, or interest arising from your filing.</LI>
        <LI>Where your situation is complex or uncertain, you should consult a qualified tax professional.</LI>
      </UL>

      <H2>5. Liability</H2>
      <P>
        To the maximum extent permitted by law, MeraTax and its operators are not liable for losses arising from
        inaccurate information you provide, from calculations you did not independently verify, or from your tax
        filing decisions. This Agreement is subject to the limitation of liability set out in the Terms &amp;
        Conditions. Nothing here removes rights that cannot be waived under applicable law.
      </P>

      <H2>6. Consent to electronic records</H2>
      <P>
        You agree to receive agreements, notices, and disclosures from us electronically, and that your
        electronic acceptance has the same effect as a handwritten signature.
      </P>

      <H2>7. Updates</H2>
      <P>
        We may publish a new version of this Agreement. If we do, we will ask you to review and accept it before
        you continue using the Service.
      </P>

      <H2>8. Contact</H2>
      <P>Questions about this Agreement? Contact <strong>{CONTACT_EMAIL}</strong>.</P>
    </LegalLayout>
  );
}
